#! /bin/bash

absDir="$(cd $(dirname $0); pwd -P)"
if ! ls ~/.config/nvim/init.vim &> /dev/null; then
  ln -s "$absDir"/../vim/vimrc ~/.config/nvim/init.vim
fi

# Install vim-plug
if ! ls "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim &> /dev/null; then
  sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
fi

# Add nvim to the list of configed apps
log="$absDir"/../../logs/config.log
if ! cat $log | grep -P '^nvim$' &> /dev/null; then 
  echo nvim>>$log
fi
