#! /bin/bash

absDir="$(cd $(dirname $0); pwd -P)"
if ! ls ~/.vimrc &> /dev/null; then
  ln -s "$absDir"/vimrc ~/.vimrc
fi

# Install vim-plug
if ! ls ~/.vim/autoload/plug.vim &> /dev/null; then
  curl -fLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi

# Add vim to the list of configed apps
log="$absDir"/../../logs/config.log
if ! cat $log | grep -P '^vim$' &> /dev/null; then 
  echo vim>>$log
fi
