#! /bin/bash

# uninstall all apps installed by myConfig and listed in install.log
dir=$(dirname "$0")/../logs
if ls "$dir"/install.log &>/dev/null; then
  apps=$(cat "$dir"/install.log)
  rm "$dir"/install.log
  
  for f in $apps; do
    echo uninstalling $f ...
    if sudo apt autoremove -y $f &>/dev/null; then
      echo $f uninstalled.
    else
      echo $f could not be uninstalled.
      echo $f>>"$dir"/install.log
    fi
  done
else
  echo Nothing to uninstall.
fi
