#colors!
    red="\033[1;31m"
  green="\033[0;32m"
 yellow="\033[1;33m"
   blue="\033[1;34m"
magenta="\033[1;35m"
   cyan="\033[1;36m"
  white="\033[0;37m"
    end="\033[0m" # This is needed at the end... :(

PS1="${red}Home:${green}\w${white}>"
